databases:
  - name: skillconnect-db
    databaseName: skillconnect
    user: skillconnect
    plan: free

services:
  - type: web
    name: skillconnect-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillconnect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.0
